### HTML ENDPOINTs 
### Get the index
GET http://127.0.0.1:3000/

### Get the index
GET http://127.0.0.1:3000/

### Get the homepage
GET http://127.0.0.1:3000/pages/homepage

### HTML API DOCUMENTATION
GET http://127.0.0.1:3000/detail



### API ENDPOINTS
### Login Request
POST http://127.0.0.1:3000/api/login
Content-Type: application/json

{
    "email": "admin@nku.edu",
    "password": "admin"
}

### MongoDB Users
GET http://127.0.0.1:3000/api/users

### MongoDB single user
GET http://127.0.0.1:3000/api/users/admin@nku.edu

### MongoDB Courses
GET http://127.0.0.1:3000/api/courses

### MongoDB single course
GET http://127.0.0.1:3000/api/courses/68014c3cd90a7b7c7ad7ee05

### Update the content of a document
POST http://127.0.0.1:3000/api
Content-Type: application/json

{"test": true}

### Change the content of a document
PUT http://127.0.0.1:3000/api
Content-Type: application/json

{"test": true}

### Delete the content of a document
DELETE http://127.0.0.1:3000/api
